### ISSUE TITLE
Nice Stuff

### ISSUE THREAD

**Issue by imohchard** [kayslay/hotels#1]
I plan on using the API for a school project.. on android.
Just one issue:
Would it be possible for it to run an image or a link to an image?
Meaning the picture of the hotel

**Comment by kayslay** [comment]
Thanks for the reply. It means a lot.

Would create a crawler that would extract the images from hotel.ng when I
am free.

**Comment by imohchard** [comment]
You welcome.
Is there a way you can implement it soon enough.
Might want to use it for a project

**Comment by kayslay** [comment]
@imohchard this my not be added soon, due to the limits of the web crawler am using
